### ISSUE TITLE
A modification on PlotRawData function

### ISSUE THREAD

**Issue by NourMarzouka** [BILS/shiny-baseline-correction-Cancer-CN#1]
# to remove the small regions from the plot and the density plot, this line should be added:
# if(hasArg(markers)){    sam<-sam[which(sam$Num.of.Markers>markers),]  }
# in this way:

PlotRawData<-function(object, select=1, plots=TRUE,cutoff=0.1,markers=20, comments =FALSE,...){

  name <- object$SL[select,"Sample"] # get the sample name
  sam <- object$regions[which(object$regions$Sample %in% as.character(name)),]   #get the sample segments

  if(hasArg(markers)){ sam <- sam[ which(sam$Num.of.Markers>markers), ]  }

.
.
.
.

**Comment by jhagberg** [comment]
Updated in commit  f6262a4b0f9c785e337d589191a4443a675dda42
