### ISSUE TITLE
TCGA tab

### ISSUE THREAD

**Issue by NourMarzouka** [BILS/shiny-baseline-correction-Cancer-CN#4]
I can not plot the TCGA data, because there is no "plot" button.
in the TCGA tab always there is this error: object 't1' not found

**Comment by jhagberg** [comment]
You can plot if you switch to the plot tab.
But you would like the same function as the other tabs "forward to plot?"

**Comment by NourMarzouka** [comment]
it does not plot when i switch to the plot tab.
Plot function will be nice if it easy to do.

**Comment by jhagberg** [comment]
"t1" bug is fixed with #7

**Comment by jhagberg** [comment]
Fixed with pull req #8
