### ISSUE TITLE
Plot raw tab

### ISSUE THREAD

**Issue by NourMarzouka** [BILS/shiny-baseline-correction-Cancer-CN#5]
The "select all samples", select only the displayed samples but not all the samples in the user data.
For example is the user has 100 samples and he showed only 5 samples in the raw tab, then he select the option "select all samples", this will give him only 5 samples in the Autocorrection tab.
It should select all the samples in the user data (the 100 samples).

**Comment by jhagberg** [comment]
Need more information as I think this is not what I understood from you earlier. 

So Manual correction should only be available to the selected plots?

**Comment by jhagberg** [comment]
What about add a checkbox "Select all samples from dataset (## total numbers" 
and rename the current checkbox to
"Select all displayed plot for manual correction" 

More than that I do not think we have free time for. You are always welcome to submit a new support request and pay for extra support.

**Comment by NourMarzouka** [comment]
"Select all samples from dataset" 
"Select all displayed plot for manual correction"
buttons idea is a good idea

**Comment by jhagberg** [comment]
Should the download plots function create a plot for every sample in the data set when using the checkbox "Select all samples from dataset" ? or only the one selected and plotted on the webpage or selected by checking the.  "Select all displayed plot for manual correction"

**Comment by NourMarzouka** [comment]
good point...if we can make two buttons, one for all samples in data set, and another for the selected samples only. is that possible?

**Comment by jhagberg** [comment]
I sent a mail separately about this.
