### ISSUE TITLE
saved plots

### ISSUE THREAD

**Issue by NourMarzouka** [BILS/shiny-baseline-correction-Cancer-CN#6]
The size of the saved plots are small. It is much better if the saved plots are bigger.

**Comment by jhagberg** [comment]
Here is the options. 

png(filename = "Rplot%03d.png",
    width = 480, height = 480, units = "px",
    pointsize = 12, bg = "white",  res = NA, ...,
    type = c("cairo", "Xlib", "quartz"), antialias)

Please update case or submitt a pull request with your prefered size. 

edit row 582 in server.r

**Comment by jhagberg** [comment]
I just added you as a collaborator. 

clone the code create a new branch 
with 
`git checkout -b feature/biggerplots`

Make your changes and then commit.  And pusch the new branch to github  by:

`git push origin feature/biggerplots`

Then you can select that branch and create a new pull request.

**Comment by NourMarzouka** [comment]
width = 1920 
height = 1200

**Comment by jhagberg** [comment]
Fixed with #9
